/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rentcarproject;

/**
 *
 * @author user
 */
public class HomeLobby extends javax.swing.JFrame {

    /**
     * Creates new form HomeLobby
     */
    public HomeLobby() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        riwayattransaksi = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        CreateAccount = new javax.swing.JButton();
        DataAccount = new javax.swing.JButton();
        daftarpelanggan = new javax.swing.JButton();
        daftarmobil = new javax.swing.JButton();
        dataakun = new javax.swing.JButton();
        datamobil = new javax.swing.JButton();
        transaksi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        riwayattransaksi.setBackground(new java.awt.Color(0,0,0,0));
        riwayattransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayattransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(riwayattransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 480, 250, 110));

        Home.setBackground(new java.awt.Color(0,0,0,0));
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 140, 130));

        CreateAccount.setBackground(new java.awt.Color(0,0,0,0));
        CreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountActionPerformed(evt);
            }
        });
        getContentPane().add(CreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 140, 120));

        DataAccount.setBackground(new java.awt.Color(0,0,0,0));
        DataAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataAccountActionPerformed(evt);
            }
        });
        getContentPane().add(DataAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 140, 130));

        daftarpelanggan.setBackground(new java.awt.Color(0,0,0,0));
        daftarpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarpelangganActionPerformed(evt);
            }
        });
        getContentPane().add(daftarpelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 260, 110));

        daftarmobil.setBackground(new java.awt.Color(0,0,0,0));
        daftarmobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarmobilActionPerformed(evt);
            }
        });
        getContentPane().add(daftarmobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 250, 110));

        dataakun.setBackground(new java.awt.Color(0,0,0,0));
        dataakun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataakunActionPerformed(evt);
            }
        });
        getContentPane().add(dataakun, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 260, 110));

        datamobil.setBackground(new java.awt.Color(0,0,0,0));
        datamobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datamobilActionPerformed(evt);
            }
        });
        getContentPane().add(datamobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 250, 110));

        transaksi.setBackground(new java.awt.Color(0,0,0,0));
        transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiActionPerformed(evt);
            }
        });
        getContentPane().add(transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 320, 250, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\EMS\\Aset_Gambar\\Frame 5.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_HomeActionPerformed

    private void CreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountActionPerformed
        // TODO add your handling code here:
        BuatAkun daftarakun = new BuatAkun();
        daftarakun.setVisible(true);
    }//GEN-LAST:event_CreateAccountActionPerformed

    private void DataAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataAccountActionPerformed
        // TODO add your handling code here:
        DataAkun data = new DataAkun();
        data.setVisible(true);
    }//GEN-LAST:event_DataAccountActionPerformed

    private void daftarpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarpelangganActionPerformed
        // TODO add your handling code here:
        DaftarPelanggan daftar1 = new DaftarPelanggan();
        daftar1.setVisible(true);
    }//GEN-LAST:event_daftarpelangganActionPerformed

    private void dataakunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataakunActionPerformed
        // TODO add your handling code here:
        DataPelanggan data2 = new DataPelanggan();
        data2.setVisible(true);
    }//GEN-LAST:event_dataakunActionPerformed

    private void daftarmobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarmobilActionPerformed
        // TODO add your handling code here:
        DaftarMobil data1 = new DaftarMobil();
        data1.setVisible(true);
    }//GEN-LAST:event_daftarmobilActionPerformed

    private void datamobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datamobilActionPerformed
        // TODO add your handling code here:
        DataMobil data3 = new DataMobil();
        data3.setVisible(true);
    }//GEN-LAST:event_datamobilActionPerformed

    private void transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiActionPerformed
        // TODO add your handling code here:
        Transaksi datatransaksi = new Transaksi();
        datatransaksi.setVisible(true);
    }//GEN-LAST:event_transaksiActionPerformed

    private void riwayattransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayattransaksiActionPerformed
        // TODO add your handling code here:
        RiwayatTransaksi riyawattransaksi = new RiwayatTransaksi();
        riyawattransaksi.setVisible(true);
    }//GEN-LAST:event_riwayattransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeLobby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateAccount;
    private javax.swing.JButton DataAccount;
    private javax.swing.JButton Home;
    private javax.swing.JButton daftarmobil;
    private javax.swing.JButton daftarpelanggan;
    private javax.swing.JButton dataakun;
    private javax.swing.JButton datamobil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton riwayattransaksi;
    private javax.swing.JButton transaksi;
    // End of variables declaration//GEN-END:variables
}
